### ISSUE TITLE
Make finding of PRS files for Sonic Adventure DX case sensitive

### ISSUE THREAD

**Issue by tydog98** [shawngmc/game-extraction-toolbox#16]
If you are running on a Windows machine everything will work fine because Windows uses a case insensitive filesystem. Linux on the other hand, uses a case sensitive filesystem. The files the script is looking for are named in caps, but the script searches for lowercase. This leads to Linux users having to rename the files in lower case for the script to find them.

**Comment by shawngmc** [comment]
This should be fixed in the next release.

**Comment by tydog98** [comment]
Awesome
