### ISSUE TITLE
Future: Zombies Ate My Neighbors and Ghoul Patrol

### ISSUE THREAD

**Issue by Feilakas** [shawngmc/game-extraction-toolbox#20]
Concerning the Zombies Ate My Neighbors and Ghoul Patrol games collection, the games are included in unaltered form inside the "ZAMN_GP.exe" executable and can be extracted with a simple hex copy/paste operation.
It is important to note that the executables for the Steam and GOG releases differ and as such, the offsets are also different.

In the following example I am using the dd tool which is available for both Windows and Linux OSes. The syntax is as it would be for Windows.

For Steam the commands are the following:
".\dd.exe" "if=%mydir%\ZAMN_GP.exe" "of=%mydir%\Ghoul Patrol (USA).sfc" bs=1 skip=26880448 count=1048576
".\dd.exe" "if=%mydir%\ZAMN_GP.exe" "of=%mydir%\Zombies Ate My Neighbors (USA).sfc" bs=1 skip=28360012 count=1048576

For GoG the commands are the following:
".\dd.exe" "if=%mydir%\ZAMN_GP.exe" "of=%mydir%\Ghoul Patrol (USA).sfc" bs=1 skip=26867136 count=1048576
".\dd.exe" "if=%mydir%\ZAMN_GP.exe" "of=%mydir%\Zombies Ate My Neighbors (USA).sfc" bs=1 skip=28346700 count=1048576 

The "Ghoul Patrol (USA).sfc" MD5 should be: 657FA94CFF4464CBC58C476EA642299A
The  "Zombies Ate My Neighbors (USA).sfc" MD5 should be: 23C2AF7897D9384C4791189B68C142EB

**Comment by shawngmc** [comment]
This is in the dev branch/upcoming release.

**Comment by shawngmc** [comment]
Added in v0.1.0.
