### ISSUE TITLE
SNK 40th Anniversary Collection

### ISSUE THREAD

**Issue by Feilakas** [shawngmc/game-extraction-toolbox#30]
This collection is playable almost in its' entirety. Relatively few things are missing:
- **psychosj** appears to have corrupt PCM audio. It sounds like the English audio (but garbled) instead of the Japanese audio. Easily noticeable in the song during attract mode.
- The **btlfield** / **timesold** ROMs are not playable under Current MAME because the *"ym2413_instruments.bin"* file is missing.
It might be that this hasn't yet been identified/extracted or that it simply wasn't included but rather re-implemented. FB Neo doesn't seem to need it (like qsound) so it works as-is.
- **gwarb** appears to have an incorrect *"g01"* file and will not work. Under FBNeo it fails the CRC check while under Current MAME it is stuck in an endless loop during the initial system check.
- Interestingly, it appears that there are enough "CRC-correct" files to create the **gwarab** ROM. By "re-using" the (CRC incorrect) files *"horizon.8j"*, *"vertical.8k"*, *"l.1w"* and *"l.1x"* from **gwara**, it can be made to run under Current MAME. Under FBNeo it runs even without adding said files.
- **legofair** is missing the *"horizon.6h"* and *"vertical.7h"* files. These files are also included in **bermudata**, **gwara**, **psychos**, **psychosj** and **worldwar** and despite the different file extensions, they are in fact common across all ROMs and can be easily taken from any of them.
- **bermudata** seems to have two unneeded files: *"l.1d"* and *"l.2d"*.
- **worldwar** similarly has the same unneeded files and is also missing the PCM audio files *"p4.5e"* and *"p5.5g"*. By renaming the unneeded files into the missing files, Current MAME can be "tricked" into running the ROM but as expected, the PCM speech/sounds are missing. Interestingly, if we instead add other PCM files such as those from **dogosoke/victroad**, the speech from that game will be heard, meaning the files are more-or-less interchangeable.

**Comment by shawngmc** [comment]
> This collection is playable almost in its' entirety. Relatively few things are missing:
> 
> * **psychosj** appears to have corrupt PCM audio. It sounds like the English audio (but garbled) instead of the Japanese audio. Easily noticeable in the song during attract mode.

Accidentally was injecting the english audio file. Fixed.

> * The **btlfield** / **timesold** ROMs are not playable under Current MAME because the _"ym2413_instruments.bin"_ file is missing.
>   It might be that this hasn't yet been identified/extracted or that it simply wasn't included but rather re-implemented. FB Neo doesn't seem to need it (like qsound) so it works as-is.

Correct. Unfortunately, there's no source for the YM2413 code in the bundle file. It appears to have been re-implemented. As such, while I can't supply that code, it's at least playable on older MAME. No action, unforunately.

> * **gwarb** appears to have an incorrect _"g01"_ file and will not work. Under FBNeo it fails the CRC check while under Current MAME it is stuck in an endless loop during the initial system check.
> * Interestingly, it appears that there are enough "CRC-correct" files to create the **gwarab** ROM. By "re-using" the (CRC incorrect) files _"horizon.8j"_, _"vertical.8k"_, _"l.1w"_ and _"l.1x"_ from **gwara**, it can be made to run under Current MAME. Under FBNeo it runs even without adding said files.

It appears the what I had as 'gwarb' is actually 'gwarab'. This makes a lot of sense; 'gwarb' is a hacked version, whereas 'gwarab' is another official revision. The maincpu labeled 'b' is actually the right CRC for the 'gwarab' maincpu. Fixed.

> * **legofair** is missing the _"horizon.6h"_ and _"vertical.7h"_ files. These files are also included in **bermudata**, **gwara**, **psychos**, **psychosj** and **worldwar** and despite the different file extensions, they are in fact common across all ROMs and can be easily taken from any of them.

We don't have real versions of this file, and it ran without placeholders - but I agree that this is a fluke. Fixed via adding placeholders.

> * **bermudata** seems to have two unneeded files: _"l.1d"_ and _"l.2d"_.

Ah, I see - these are listed in the ROM set, but there is no dump for them, so a placeholder is unnecessary. Fixed.

> * **worldwar** similarly has the same unneeded files and is also missing the PCM audio files _"p4.5e"_ and _"p5.5g"_. By renaming the unneeded files into the missing files, Current MAME can be "tricked" into running the ROM but as expected, the PCM speech/sounds are missing. Interestingly, if we instead add other PCM files such as those from **dogosoke/victroad**, the speech from that game will be heard, meaning the files are more-or-less interchangeable.

I found the ADPCM data I had overlooked. It's extracted and working. Fixed.

**Comment by Feilakas** [comment]
Sorry for re-opening but I discovered a minor thing which is an easy fix.

For victroad you are using a placeholder "a5004-1.6d" file.
However, the "real" file is in fact included as file "p-a1.2c" of the chopperb ROM.

CRC: 311E5AE6 
MD5: E8B3403E85E7DDE4E118989E41B365C5
