### ISSUE TITLE
SNK 40th Anniversary - Still missing Bermuda Triangle

### ISSUE THREAD

**Issue by Feilakas** [shawngmc/game-extraction-toolbox#37]
Certainly not a knock since I myself missed it for several months but, apparently, "Bermuda Triangle" is still missing.

The tool DOES extract **A** ROM that is named "Bermuda Triangle" named *"bermudata"* .
However, that rom is NOT a version of **Bermuda Triangle** but a clone of **World Wars** *(worldwar)* which is also being extracted.
The "real" ROM is the *"bermudat"* (without an "a" at the end). Apparently the two games do share SOME assets (like the music) and game logic but have completely different sprites, enemies and stages.

The good news is that the tool already extracts 6 of the required files for the game:

p1.4p with CRC: 43DEC5E9 and MD5: E5B0A13269955A9D3FC37D08B53F621E
p2.8p with CRC: 0E193265 and MD5: 26CBCEAF99571975805DE1B52B2DAD6E
p3.7k with CRC: 53A82E50 and MD5: 43548696639CD144DCFF3E10E14B94C7
p4.5e with CRC: 4BC83229 and MD5: E94EC1C32160EE667E8515FD5DF7916B
p5.5g with CRC: 817BD62C and MD5: D3EE2FF01A4DA8B928728B2FD4948FABD2B04420
p10.3a with CRC: D3650211 and MD5: CC7CFE05C5903CAF33F8F02C416F68E6D2F6BAA7

The bad news is that there are still 21 files missing - 19 of which are unique to this game plus the "horizon.6h" and "vertical.7h" which are common to many of the games:

1.1k with CRC: F4B54D06 and MD5: 1AE260BFBAA907857873D677A8346EA8
2.1l with CRC: BAAC139E and MD5: 646413DDEDDE64895BA3F3C8B9C30E4C
3.2l with CRC: 2EDF2E0B and MD5: 4F7F7CD2A52836AE0F47972C7608AC6B

p6.3g with CRC: 8FFDF969 and MD5: 5B3970DC2C1C2F1D677511B8C2874869
p7.3e with CRC: 268D10DF and MD5: DBFCBA9ECDB8828A8AB502CD0A06836E
p8.3d with CRC: 3E39E9DD and MD5: C2101A92063FA67A11670441E5B18ED5
p9.3b with CRC: BF56DA61 and MD5: 0EA303B845E71EF33EBC20F074898FCE
p11.7p with CRC: AAE7410E and MD5: BBE91740F8BCC1DEBC6BB290485F7C73
p12.7s with CRC: 18914F70 and MD5: C7AA6A8068930800A82F8467C6D5C33F
p13.8h with CRC: CD79CE81 and MD5: C341E40562036218DC1B0CEECF6B7FCC
p14.8k with CRC: EDC57117 and MD5: 587137706C6DF05C47C8757EF90DEC5F
p15.8m with CRC: 448BF9F4 and MD5: CE73003FA0C0E9B8D0A554A3DF86A140
p16.8n with CRC: 119999EB and MD5: D8B397ACB29DDC55480F902F6D91477A
p17.8p with CRC: B5462139 and MD5: 88CDC7CFC6F3895ACABABAD4035BA431
p18.8s with CRC: CB416227 and MD5: E0F54020DA557AD3AD8DFFBB9A0AD9FE
p19.1a with CRC: 8ED759A0 and MD5: E50F60787C0E8F88DC87C26B9CE34830
p20.1b with CRC: AB6217B7 and MD5: 4087A6ECFB11CCBCCBF0C56B89D0A68E
p21.1d with CRC: B7689599 and MD5: E5AE915C0B36817BCC62FEA3B3596162
p22.1e with CRC: 8DAF7DF4 and MD5: 974BBDD62A067B8CB92B5CB32CFC34A9

horizon.6h with CRC: C20B197B and MD5: DE3622F7781D634A0334429473FE4811
vertical.7h with CRC: 5D0C617F and MD5: FB2925C0AE63451488DB26927466878E

**Comment by charlieglide** [comment]
FWIW, it is on SNK Arcade Classics 0 for the PSP.  So that is an alternate source.

**Comment by shawngmc** [comment]
So, according to [Arcade Italia](http://adb.arcadeitalia.net/):

**All 'World Wars' Variants**

- BERMUDAA	Bermuda Triangle (World Wars) (US)	Inactive as of .132u5
- BERMUDATA	Bermuda Triangle (World Wars) (US)	Active
- WORLDWAR	World Wars (World?)			Active

**All 'Bermuda Triangle' Variants**

- BERMUDAO	Bermuda Triangle (Japan old version)	Inactive as of .127
- BERMUDAJ	Bermuda Triangle (Japan)		Inactive as of .132u5
- BERMUDATJ	Bermuda Triangle (Japan)		Active
- BERMUDAT	Bermuda Triangle (World?)		Active

As such, we need to figure out if we have enough to build BERMUDAO, BERMUDAJ, BERMUDATJ or BERMUDAT. It could be one of these older variants.

**Comment by shawngmc** [comment]
We have the following files that we aren't pulling from yet:

- BermudaTriangle.0.z80
- BermudaTriangle.1.z80
- BermudaTriangle.2.z80
- BermudaTriangle.adpcm
- BermudaTriangle.bg
- BermudaTriangle.j.0.z80
- BermudaTriangle.j.2.z80
- BermudaTriangle.j.adpcm
- BermudaTriangle.pal
- BermudaTriangle.sp
- BermudaTriangle.sp32
- BermudaTriangle.tx

Given that we have a set of english and japanese (.j.) files, presumably we have bermudatj and bermudat.

And... we do. I think we've got them! :)
