### ISSUE TITLE
Future: Breakers Collection

### ISSUE THREAD

**Issue by tydog98** [shawngmc/game-extraction-toolbox#47]
This game on Steam contains both Breakers and Breakers Revenge. In the game install there are two folders under BreakersCollection_Data/StreamingAssets for both breakers and breakrev, zipping the files from these folders produces breakers.zip and breakrev.zip. They are both playable under the "Current" MAME Retroarch core.

The beta for this game is currently free

**Comment by Feilakas** [comment]
Can confirm.

Currently the game is in pre-release form (releases 12th Jan 2023) but the demo is available for download.
At the moment (there is still time until the game's release) the ROM files are sitting in unaltered form in the game's folders and only need a rename.
There are also two files that are not part of the ROMs, **dummy.dat** and **vm_bios.bin** . Maybe they are BIOS substitutes?

The easiest way I found to properly rename and "assemble" the files into ROMs is to use [ClrMamePro]https://mamedev.emulab.it/clrmamepro/#downloads(url), load the latest [MAME xml]https://www.mamedev.org/release.html(url) and then use ClrMamePro to scan the game's folders.

The manual way would of course be to check each file's CRC one by one and rename accordingly (not fun).

**Comment by tydog98** [comment]
Yeah I've been using ROM Center + the Arcade Itialia xml

**Comment by charlieglide** [comment]
Thank you so much for this information.  I just played them both on MAME.

**Comment by shawngmc** [comment]
I know ClrMamePro can try to identify things, but I've been scripting these
out more concretely, even if just renaming things.

I will take a look at this collection when I get a chance - good find!

**Comment by shawngmc** [comment]
This will be in 0.1.7!

**Comment by shawngmc** [comment]
Implemented in 0.1.7.
